[build]
  command = "python build.py"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/survey.html"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200